# 3.6 损失函数

In [104]:
import torch
import torch.nn as nn
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
print(target)
output = loss(m(input), target)
output.backward()

print('BCELoss损失函数的计算结果为',output)

tensor([0., 0., 0.])
BCELoss损失函数的计算结果为 tensor(0.4646, grad_fn=<BinaryCrossEntropyBackward0>)


In [149]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

# input = torch.tensor([[0, 0, 12, 0, 0], [0, 0, 0, 12, 0], [0, 0, 0, 0, 12]], dtype=float, requires_grad=True)
# target = torch.tensor([2, 3, 4], dtype=torch.long)

output = loss(input, target)
print(input, target)
output.backward()

print(output)

tensor([[ 0.,  0., 12.,  0.,  0.],
        [ 0.,  0.,  0., 12.,  0.],
        [ 0.,  0.,  0.,  0., 12.]], dtype=torch.float64, requires_grad=True) tensor([2, 3, 4])
tensor(2.4577e-05, dtype=torch.float64, grad_fn=<NllLossBackward0>)


In [155]:
loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()
print(input, target)

print('L1损失函数的计算结果为',output)

tensor([[-1.3978, -1.5244, -0.3794, -0.1591,  0.7434],
        [ 0.5984, -0.5284,  1.6001, -1.0425,  0.8585],
        [ 1.6198, -1.6599, -1.7279,  0.0155,  0.3969]], requires_grad=True) tensor([[ 0.5336,  0.9781,  0.2446,  0.2799, -0.1369],
        [-1.5538,  1.1776,  1.2291, -0.5504,  0.3049],
        [ 0.1673,  0.6074, -0.8998,  1.7977,  0.4949]])
L1损失函数的计算结果为 tensor(1.2054, grad_fn=<MeanBackward0>)


In [156]:
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()
print(input, target)

print('MSE损失函数的计算结果为',output)

tensor([[-1.5827, -0.4545,  0.5721, -0.0782,  1.4857],
        [ 0.1584, -0.8874,  0.7323,  1.0446,  0.0632],
        [ 0.3814, -0.0906, -0.5416,  0.5895, -1.4013]], requires_grad=True) tensor([[ 1.3658,  0.6780,  0.6126,  0.7548, -0.2695],
        [-0.8074, -0.5349, -0.3989, -0.9855,  0.9337],
        [ 0.6956, -0.5423,  1.4421,  0.1873, -0.2964]])
MSE损失函数的计算结果为 tensor(1.7725, grad_fn=<MseLossBackward0>)


In [154]:
loss = nn.SmoothL1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()
print('SmoothL1Loss损失函数的计算结果为',output)

SmoothL1Loss损失函数的计算结果为 tensor(0.6074, grad_fn=<SmoothL1LossBackward0>)


In [157]:
loss = nn.PoissonNLLLoss()
log_input = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
output = loss(log_input, target)
output.backward()
print('PoissonNLLLoss损失函数的计算结果为',output)


PoissonNLLLoss损失函数的计算结果为 tensor(1.6761, grad_fn=<MeanBackward0>)


In [316]:
loss = nn.PoissonNLLLoss()
log_input = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
output = loss(log_input, target)
output.backward()

print('PoissonNLLLoss损失函数的计算结果为',output)

PoissonNLLLoss损失函数的计算结果为 tensor(1.2162, grad_fn=<MeanBackward0>)


In [320]:
inputs = torch.tensor([[0.5, 0.3, 0.2], [0.2, 0.3, 0.5]])
target = torch.tensor([[0.9, 0.05, 0.05], [0.1, 0.7, 0.2]], dtype=torch.float)
loss = nn.KLDivLoss()
output = loss(inputs,target)

print('KLDivLoss损失函数的计算结果为',output)

KLDivLoss损失函数的计算结果为 tensor(-0.3335)
